FORMAT: 1A

# Hexgame

Hexgame is a protocol allowing users to create and play games based on 
hex boards.

# Group Users

## User Collection [/users]

### Get a List of Users [GET]

    + Response 200 (application/json)

### Create a New User [POST]

    + Response 201 (application/json)
      + Headers
        + Location /users/1

## A Single User [/users/{user_id}]

### Get a User [GET]

    + Response 200 (application/json)

### Update a User [PUT]

    + Response 

# Group Games

## Game Collection [/games]

# Group Maps

## Map Collection [/maps]

### List All Maps [GET]

### Create A New Map [POST]

## A Single Map [/maps/{map_id}]

### Get a Specific Map [GET]

### Update a Map [PUT]

    + Response 204 (application/json)

# Group Matches

## Match Collection [/matches]


### List All Matches [GET]
    
    + Response 200 (application/json)

### Create a New Match [POST]

    + Response 201 (application/json)
      + Headers
        Location: /matches/1
    
## Match [/matches/{match_id}]

### Get a Match [GET]

    + Response 200 (application/json)
    
    
