= Hex Games

Hex games are played on a board or map formed of a tessellation, or
tiling of hexagons or "hexes".  Hexagons are the "largest" regular
polygons that can completely fill a plane. triangles and squares can
also fill a plane, but they have fewer sides than hexagons.

The number of sides matters when trying to use the filled plane as
a map. The circle is the ideal shape to measure movement or distance
in a plane, but using proper Cartesian coordinates in a game makes the
mechanics of movement complex.  Using hexagons offers a compromise
between reality and complexity for a game mechanic.

Locating an object on a hex map becomes much simpler than on a
Cartesian plane.  In the plane, each location is noted as a pair of
real number values.  These are distances from an origin point (0,0) on
two axes.  A hex map also uses two coordinates, but the values are
integers rather than real numbers. This makes it easy to represent
the map as an array rather than just point locations for each object.

== Hex Map Components

A _HexVector_ is made up of two integer components. It represents
either a location on the map, or the distance and direction between
two hexes.  The relationships between hexes is defined in xref:geometry[Geometry]

A _HexMap_ is a region of hexes.  It is usually defined by a
HexVector indicating the size in two dimensions.  Maps can have
different shapes, though most games use a rectangular map. The
origin is assumed to be in one corner of the map. A second HexVector
is used to offset the origin from the default location when desired.

A _Hex_ is a single location on a HexMap.  A Hex location is defined
by a single HexVector.  A Hex can have zero or more associated
_Terrain_. A Hex can contain zero or more _Tokens_. 

A _Terrain_ is a modifier for hexes. Each Hex can have a set of Terrains
which describe the contents or attributes. 

A _Token_ represents a movable unit in the game. A
Token's position on the map is represented by a HexVector. The number
of Tokens that can reside in one hex is defined by the rules of the
game. Movement of Tokens is also defined by the game, in terms of the
map geometry.

[[geometry]]
== Geometry

Mathematically a HexMap is a
https://en.wikipedia.org/wiki/Hexagonal_lattice[Triangular
Lattice] formed by the centers of each hex. The distance from the
center of one hex to the center of any of the 6 adjacent hexes is 1
unit. Each hex center is surrounded by 6 others. The lines through the
center of any hex and the two opposite hexes form an axis. There are
three axes formed in this way, which is why this is a triangular
lattice.  Any hex location can be defined in terms of a coordinate in
any two of these axes. A hex has a third coordinate, but it is not
independent of the other two and can be derived trivially.

There are three axes on a triangular lattice, at an angle of 60
degrees. Since Euclid demonstrated that only two lines are needed to
define a plane, the third axis is redundant.

=== Location

A Hex location is represented by a HexVector.  A HexVector is composed
of two integers which represent the distance from the origin on each
axis.  Here, the axes are labeled _hx_ and _hy_.

----
typedef HexVector struct {
  Hx int
  Hy int
}
----

A third "coordinate", _hz_ can be derived from the other two:

[big]`hz = hy - hx`

==== Origin

The origin of a HexMap coordinate system is defined in the same way as
a Cartesian system.

----
var ORIGIN = HexVector{0, 0}
----

==== Unit Vectors

The _Unit Vectors_ are the coordinates of the set of 6 hexes
surrounding the origin.  Each represents a distance of 1 from the
origin in one of the 6 possible directions.

----
var UNIT = []HexVector{
	HexVector{ 0, -1},  // hz = -1
	HexVector{ 1,  0},  // hz = -1
	HexVector{ 1,  1},  // hz =  0
	HexVector{ 0,  1},  // hz =  1
	HexVector{-1,  0},  // hz =  1
	HexVector{-1, -1},  // hz =  0
}
----

Notice the pattern of the change of the hx, hy and hz values:

[big]`0, 1, 1, 0, -1, -1`

